#!/usr/bin/env python3
"""Scale LVGL's bundled Unscii 8 font to crisp 40 px cells, without new dependencies.

Usage: python3 scripts/vaporwave_font.py /path/to/lvgl/src/font/lv_font_unscii_8.c
"""
import re
import sys
from pathlib import Path

source = Path(sys.argv[1]).read_text()
bitmap_source = source.split("glyph_bitmap[] = {", 1)[1].split("};", 1)[0]
bitmap_source = re.sub(r"/\*.*?\*/", "", bitmap_source, flags=re.S)
bitmap = bytes(int(x, 16) for x in re.findall(r"0x([0-9a-f]+)", bitmap_source))
descriptors = re.findall(
    r"\{\.bitmap_index = (\d+), .adv_w = (\d+), .box_w = (\d+), "
    r".box_h = (\d+), .ofs_x = (-?\d+), .ofs_y = (-?\d+)\}", source
)
data = bytearray()
glyphs = ["    {0},"]
for index, advance, width, height, x, y in map(lambda row: map(int, row), descriptors[1:]):
    bits = []
    for row in range(height):
        scaled = []
        for col in range(width):
            bit = row * width + col
            scaled.extend([(bitmap[index + bit // 8] >> (7 - bit % 8)) & 1] * 5)
        bits.extend(scaled * 5)
    offset = len(data)
    bits.extend([0] * (-len(bits) % 8))
    for i in range(0, len(bits), 8):
        data.append(sum(bit << (7 - j) for j, bit in enumerate(bits[i:i + 8])))
    glyphs.append(f"    {{{offset}, {advance * 5}, {width * 5}, {height * 5}, {x * 5}, {y * 5}}},")

lines = ["    " + ", ".join(f"0x{x:02x}" for x in data[i:i + 16]) + ","
         for i in range(0, len(data), 16)]
output = '''/* Generated by scripts/vaporwave_font.py from LVGL's Unscii 8 (CC0). */
#include <lvgl.h>
static const uint8_t bitmap[] = {
''' + "\n".join(lines) + '''
};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[] = {
''' + "\n".join(glyphs) + '''
};
static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    .range_start = 32, .range_length = 96, .glyph_id_start = 1,
    .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY,
}};
static const lv_font_fmt_txt_dsc_t dsc = {
    .glyph_bitmap = bitmap, .glyph_dsc = glyphs, .cmaps = cmaps,
    .cmap_num = 1, .bpp = 1,
};
const lv_font_t vaporwave_pixel_40 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 45, .base_line = 0, .dsc = &dsc,
};
'''
target = Path(__file__).resolve().parents[1] / "boards/shields/prospector_adapter/src/layouts/vaporwave/pixel_font.c"
target.write_text(output)
